spring:
  application:
    name: eureka-provider
  datasource:
    driver-class-name:

server:
  port: 9000
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true  # 是否将自己的ip注册到eureka中，默认false 注册 主机名
    ip-address: 127.0.0.1 # 设置当前实例ip
    lease-renewal-interval-in-seconds: 30 #每一次eureka-client向eureka-server返送心跳时间的间隔
    lease-expiration-duration-in-seconds: 90 #如果90秒内eureka-server没有收到eureka-client的心跳包,则剔除该服务
  client:
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:9300/eureka #eureka-server访问路径
      defaultZone: http://eureka-server1:9400/eureka,http://eureka-server2:9500/eureka #eureka-server访问路径
    register-with-eureka: true  #注册到eureka
    fetch-registry: false #不拉取eureka路径列表

#测试配置中心的标识命名,自定义的配置
name: eureka-provider-config-github
